### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Cheffrey2000** [learn-co-curriculum/dsc-exploring-and-transforming-json-schemas#1]
I believe it was intended for the highlighted section to read: "...as there is only one artist..."

![image](https://user-images.githubusercontent.com/52893814/74049979-396a8300-49a3-11ea-802a-96ae356e3e72.png)

**Comment by hoffm386** [comment]
The instructions have changed somewhat in the latest version, so this sentence with the grammar issue is no longer present. Thanks @Cheffrey2000!

I'm going to go ahead and close this issue
